services:

  postgres:
    image: postgres:16-alpine
    container_name: tribunal-postgres

    environment:
      POSTGRES_DB: teste_implementacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d teste_implementacao"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    image: geyson12345/tribunal-backend:latest
    container_name: tribunal-backend

    environment:
      SERVER_PORT: 8080

      DB_URL: jdbc:postgresql://postgres:5432/teste_implementacao
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

      JPA_DDL_AUTO: validate
      JPA_OPEN_IN_VIEW: "false"

      FLYWAY_ENABLED: "true"
      FLYWAY_LOCATIONS: classpath:db/migration

      APP_SECURITY_USERNAME: admin
      APP_SECURITY_PASSWORD: admin123

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy


  frontend:
    image: geyson12345/tribunal-frontend:latest
    container_name: tribunal-frontend

    ports:
      - "4200:80"

    depends_on:
      - backend


volumes:
  postgres_data: